jobs:
  include:
    - stage: test
      language: node_js
      node_js: '11'
      services:
        - docker
      install:
        - docker pull vanbujm/moonbase-balena:v0.1.0-ci-v0.2.15
      script:
        - docker run -v $(pwd):/app -v $(yarn cache dir):/yarn-cache -e CODECOV_TOKEN="$CODECOV_TOKEN"
          vanbujm/moonbase-balena:v0.1.0-ci-v0.2.15 -c "cd /app && yarn --cache-folder  /yarn-cache --ignore-scripts
          && ./bin/setup-arm.sh && yarn test-ci && codecov"
      cache:
        yarn: true
stages:
  - test
notifications:
  slack:
    rooms:
      secure: eSRPPg/r5SXob2I3y1otCpIIHLRPkVbVRksHZ2GmjH3iwyFcMwBUEFtgELO94cwjlBUhp1OmRAixrhsj/X8QhNzJzCDXwlaFeIUxRTzWfmzGLlnkcsLFwaQyTxRONrkKUmnOshaeDtypTmXELXreol4O7u63n2NG5lOIkAZQ+w/yAcidyLSWyVEo9Kq9h7cZMHKoTy629fPsZlKPTKGrEhOL8bLVeOAO3ZQm71Xo/1MZwdklR+nj58rLKQcMt8CqCFQhqGYivyi0lnMm5ldS95WynGXBEF9IFde7tMD9ubrSyzwvWJ7EKv7e69yncgNRyxJwGk2Fo4XUFMlNzpCCEaBZLPL6EnOMaFV6FLLUFB+Cc7OIGfDNsgbAq5PZzt4EusKNsHhz4VHvdNJWlDTbo1Klh6CuYhle2f9lk43rW+athPdzQq7LfD3113FkVAY8ITLPYbMNarn/eNjxgLtVhqjMTwkeNqQ5stRAGTAbHjpIMk+em9xYFb3AMTUJHzlI5uBADP5S8sMNPnXij3Np5AjJEg0WwWXAZlkWVV2mDACXTcB4NwrxFGMC7ZgdkJpqiBF9VjuzA1t13UL67ANAIRFyRlFfLyZr221R6KZL7OzykAQ5iKqdNMACwNwFBcHCzbzSVVBpjqegFvIH44hyF8qfk7/B9HXXRHfP+1fgCss=
    on_success: change
    on_failure: change
